config/routes.rb
Rails.application.routes.draw do
  root 'content#index'
  get '/help', to: 'content#help', as: 'help'
  get '/privacy', to: 'content#privacy', as: 'privacy'
  get '/terms',to: 'content#terms', as: 'terms'

  post '/account/signup', to: 'user#create', as: 'create_user'
  post '/signin', to: 'session#create', as: 'signin'
  get '/signout', to: 'session#destroy', as: 'signout'

  post '/alexa' => 'alexa#ask', :as => 'alexa'

  resources :recipe

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="content has-text-centered">
      <p>
        <strong>Repeat My Recipes</strong> by <a href="http://technoir.blog">Robert Berry</a>.
        Please review the <%= link_to 'terms of service', terms_path %> and <%= link_to 'privacy policy', privacy_path %>.
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar is-light" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to 'My Recipes', recipe_index_path, :class => 'navbar-item' %>
    </div>

    <div class="navbar-end">
      <span class="navbar-item">
        <%= @current_user.name %>
      </span>
      <%= link_to 'Sign Out', signout_path, :class => 'navbar-item'%>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <title>Your recipes, repeated back to you by Alexa</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="description" content="Get help with your recipes from Alexa"/>

    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>

    <%= render 'layouts/navbar' if @current_user.present? %>
    <%= yield %>

    <%= evil_icons_sprite %>
    <%= render 'layouts/footer' %>

    <div id="csrf-token-body" token="<%= form_authenticity_token %>"></div>
  </body>
</html>